from twisted.internet.defer import Deferred
from twisted.internet.interfaces import IReactorCore

class RustPanicError(Exception): ...

def rusty_sleep(reactor: IReactorCore, seconds: int) -> Deferred: ...
def rusty_panic(reactor: IReactorCore) -> Deferred: ...
def rusty_early_panic(reactor: IReactorCore) -> Deferred: ...
