from twisted.internet.interfaces import IReactorCore
from twisted.internet.defer import Deferred

def rusty_sleep(reactor: IReactorCore, seconds: int) -> Deferred: ...
def rusty_panic(reactor: IReactorCore) -> Deferred: ...
